export const diseases = [
  { name: "anthrax cutaneous", type: "bacteriaIcon", title: "anthrax" },
  { name: "cholera", type: "bacteriaIcon" },
  { name: "dengue", type: "virusIcon" },
  { name: "ebola haemorrhagic fever", type: "virusIcon", title: "ebola" },
  { name: "enterovirus 71 infection", type: "virusIcon", title: "enterovirus" },
  { name: "influenza a/h2n2", type: "virusIcon", title: "influenza" },
  { name: "hand, foot and mouth disease", type: "virusIcon" },
  { name: "hantavirus", type: "virusIcon" },
  { name: "hepatitis a", type: "virusIcon" },
  { name: "hepatitis c", type: "virusIcon" },
  { name: "hepatitis e", type: "virusIcon" },
  { name: "hiv/aids", type: "virusIcon" },
  { name: "lassa fever", type: "virusIcon" },
  { name: "malaria", type: "parasiteIcon" },
  { name: "marburg virus disease", type: "virusIcon" },
  { name: "measles", type: "virusIcon" },
  { name: "mers-cov", type: "virusIcon" },
  { name: "mumps", type: "virusIcon" },
  { name: "pertussis", type: "bacteriaIcon" },
  { name: "plague", type: "bacteriaIcon" },
  { name: "poliomyelitis", type: "virusIcon", title: "polio" },
  { name: "rabies", type: "virusIcon" },
  { name: "rift valley fever", type: "virusIcon" },
  { name: "rubella", type: "virusIcon" },
  { name: "salmonellosis", type: "bacteriaIcon", title: "salmonella" },
  { name: "sars", type: "virusIcon" },
  { name: "shigellosis", type: "bacteriaIcon" },
  { name: "smallpox", type: "virusIcon" },
  { name: "tuberculosis", type: "bacteriaIcon" },
  { name: "tularemia", type: "bacteriaIcon" },
  { name: "vaccinia and cowpox", type: "virusIcon", title: "cowpox" },
  { name: "varicella", type: "virusIcon", title: "chickenpox" },
  { name: "yellow fever", type: "virusIcon" },
  { name: "monkeypox", type: "virusIcon" },
  { name: "zika", type: "virusIcon" },
  { name: "COVID-19", type: "virusIcon", title: "coronavirus" },
  { name: "listeriosis", type: "bacteriaIcon" },
];
